export const cards = [
  { word: "Pizza", taboo: ["Cheese", "Slice", "Pepperoni", "Italy", "Dough"] },
  { word: "Beach", taboo: ["Sand", "Ocean", "Sun", "Swim", "Waves"] },
  { word: "Rollercoaster", taboo: ["Ride", "Theme park", "Fast", "Scary", "Loop"] },
  { word: "Eiffel Tower", taboo: ["Paris", "France", "Metal", "Tall", "Landmark"] },
  { word: "Karaoke", taboo: ["Sing", "Microphone", "Music", "Song", "Stage"] },
  { word: "Nasi Lemak", taboo: ["Rice", "Coconut", "Egg", "Malaysia", "Sambal"] },
  { word: "Smartphone", taboo: ["Phone", "Call", "Apps", "Screen", "Mobile"] },
  { word: "Frog", taboo: ["Green", "Jump", "Pond", "Tadpole", "Ribbit"] },
  { word: "Spider-Man", taboo: ["Marvel", "Web", "Peter Parker", "Superhero", "Mask"] },
  { word: "Teh Tarik", taboo: ["Tea", "Milk", "Pull", "Malaysia", "Drink"] },
  { word: "Moon", taboo: ["Night", "Space", "Craters", "Tides", "Lunar"] },
  { word: "Guitar", taboo: ["Strings", "Music", "Band", "Strum", "Acoustic"] },
  { word: "Library", taboo: ["Books", "Quiet", "Read", "Shelves", "Study"] },
  { word: "Zombie", taboo: ["Dead", "Undead", "Brain", "Horror", "Apocalypse"] },
  { word: "Volcano", taboo: ["Lava", "Eruption", "Mountain", "Magma", "Ash"] },
  { word: "BTS", taboo: ["K-pop", "Korea", "Boy band", "Music", "Army"] },
  { word: "Penguin", taboo: ["Black", "White", "Ice", "Antarctica", "Waddle"] },
  { word: "Disco", taboo: ["Dance", "70s", "Ball", "Music", "Fever"] },
  { word: "Mamak", taboo: ["Stall", "Food", "Roti", "Malaysia", "Teh Tarik"] },
  { word: "Mermaid", taboo: ["Fish", "Tail", "Ocean", "Siren", "Ariel"] },
  { word: "TikTok", taboo: ["App", "Video", "Dance", "Viral", "Short"] },
  { word: "Cendol", taboo: ["Dessert", "Ice", "Gula Melaka", "Coconut", "Green"] },
  { word: "Dinosaur", taboo: ["Extinct", "T-Rex", "Fossil", "Prehistoric", "Jurassic"] },
  { word: "Durian", taboo: ["Spiky", "Smelly", "Fruit", "King", "Malaysia"] },
  { word: "Fireworks", taboo: ["Explosion", "Sky", "Celebrate", "Boom", "Sparkle"] },
  { word: "Airplane", taboo: ["Fly", "Wings", "Airport", "Pilot", "Sky"] },
  { word: "Dragon", taboo: ["Fire", "Wings", "Mythical", "Scales", "Chinese"] },
  { word: "Halloween", taboo: ["Costume", "Candy", "Pumpkin", "October", "Scary"] },
  { word: "Bubble tea", taboo: ["Pearls", "Tapioca", "Drink", "Taiwan", "Straw"] },
  { word: "Satay", taboo: ["Skewers", "Peanut", "Grill", "Meat", "Malaysia"] },
];
