export const prompts = [
  "Pineapple on pizza is elite.",
  "Stranger Things is overrated.",
  "Social media does more harm than good.",
  "Cats are better pets than dogs.",
  "Coffee tastes better than tea.",
  "Cold showers are better than hot ones.",
  "Star Wars is better than Star Trek.",
  "Mondays are actually the best day of the week.",
  "Chocolate should be stored in the fridge.",
  "Country music is better than hip-hop.",
  "Working from home is worse than the office.",
  "Video games are a real sport.",
  "Disney movies are not for adults.",
  "Ketchup belongs on pasta.",
  "Mornings are better than nights.",
  "Books are always better than the movie.",
  "Peanut butter is the best condiment.",
  "Vans are better than Converse.",
  "Spicy food is a personality trait.",
  "No one actually enjoys running.",
  "TikTok is destroying attention spans.",
  "Avocados are overrated.",
  "Android is better than iOS.",
  "The beach is better than the mountains.",
  "Cereal is a soup.",
  "Hot dogs are not sandwiches.",
  "Marvel movies are all the same.",
  "Crocs are fashionable.",
  "Sleeping in is always worth it.",
  "A hot dog is a taco.",
];
