export const prompts = [
  "Most likely to become a CEO before 35",
  "Most likely to accidentally go viral on TikTok",
  "Most likely to marry a stranger they met on a plane",
  "Most likely to survive a zombie apocalypse",
  "Most likely to cry at a Disney movie",
  "Most likely to become a celebrity",
  "Most likely to get lost in their own neighbourhood",
  "Most likely to still be gaming at 3am on a Tuesday",
  "Most likely to move to another country",
  "Most likely to write a tell-all memoir",
  "Most likely to forget their own birthday",
  "Most likely to become a social media influencer",
  "Most likely to quit everything and open a café",
  "Most likely to argue with a Wikipedia article",
  "Most likely to show up underdressed to a wedding",
  "Most likely to invent something ridiculous that actually works",
  "Most likely to accidentally insult someone while trying to compliment them",
  "Most likely to be on the news one day (for good or bad)",
  "Most likely to be 30 minutes late to their own wedding",
  "Most likely to spend their whole salary in one day",
  "Most likely to forget they have a meeting until 5 minutes before",
  "Most likely to befriend a random stranger on public transport",
  "Most likely to think a movie's ending was deeper than it was",
  "Most likely to become obsessed with a niche hobby",
  "Most likely to get kicked out of an escape room for breaking something",
  "Most likely to order food and then immediately regret it",
  "Most likely to cause a scene at a buffet",
  "Most likely to be cancelled on social media",
  "Most likely to have an existential crisis at a party",
  "Most likely to be the first to fall asleep on a trip",
];
