export const truths = [
  "What's the most embarrassing thing you've done in public?",
  "What's the worst lie you've ever told?",
  "What's a secret you've never told anyone in this room?",
  "Have you ever cheated on a test or exam?",
  "What's the last thing you searched on Google that you'd be embarrassed about?",
  "Who in this room would you swap lives with for a week?",
  "Have you ever pretended to be sick to avoid someone?",
  "What's the most childish thing you still do?",
  "Have you ever said 'I love you' and not meant it?",
  "What's your biggest fear that nobody knows about?",
  "Have you ever stolen anything, even something small?",
  "What's the pettiest reason you've unfollowed or blocked someone?",
  "Have you ever ghosted someone you actually liked?",
  "What's the most embarrassing thing in your camera roll right now?",
  "When was the last time you cried and what caused it?",
  "Who was your first crush in this room? (If applicable)",
  "What's the most trouble you've ever been in?",
  "Have you ever talked badly about someone who's in this room?",
  "What's a habit you have that you'd be embarrassed if people found out?",
  "What's your worst date story?",
  "Have you ever blamed someone else for something you did?",
  "What's the weirdest thing you've Googled at 2am?",
  "Have you ever eaten food you dropped on the floor and said nothing?",
  "What's something you pretend to like but secretly can't stand?",
  "Have you ever read someone's messages without their knowledge?",
  "What's the most money you've spent on something embarrassing?",
  "Have you ever laughed so hard you peed a little?",
  "What's a childish fear you still have?",
  "Who's the last person you stalked on social media?",
  "What's the worst thing you've ever said to a family member?",
];

export const dares = [
  "Do your best impression of someone in this room right now.",
  "Send a voice note to the last person you texted saying 'I have something important to tell you.'",
  "Let someone post anything they want to your Instagram or WhatsApp status for 60 seconds.",
  "Do 20 push-ups right now. No breaks.",
  "Speak only in an accent of the group's choice for the next 3 rounds.",
  "Call a family member and say 'I need to confess something' — then say 'I ate the last snack. Bye.'",
  "Do your best robot dance for 30 seconds straight.",
  "Let the person next to you go through your camera roll for 30 seconds.",
  "Eat a full spoonful of the spiciest condiment available.",
  "Hold a plank for 45 seconds.",
  "Speak only in questions until it's your turn again.",
  "Let someone change your phone wallpaper to whatever they choose.",
  "Give every person in the room one genuine, specific compliment.",
  "Go outside and yell 'I BELIEVE I CAN FLY!' at full volume.",
  "Do a TikTok dance of the group's choice.",
  "Let the group style your hair however they want for the rest of the game.",
  "Call the 5th contact in your phone and sing Happy Birthday to them.",
  "Text your most recent ex the word 'hey' and show everyone their reply.",
  "Do your best impression of a Grab driver calling to say he can't find the pickup point.",
  "Show the group the last 10 photos in your camera roll without skipping any.",
  "Let the group write and send one tweet or IG story from your account.",
  "Do a dramatic reading of your most cringe text conversation.",
  "Switch clothes with the person to your left for the next 2 rounds.",
  "Do 10 jumping jacks while reciting your full name, IC number, and current address.",
  "Stare into someone's eyes without blinking for 30 seconds.",
  "Do your best catwalk across the room and back.",
  "Try to lick your elbow in front of everyone.",
  "Let the group pick a word you must say in every sentence until your next turn.",
  "Recreate the most embarrassing photo from your camera roll.",
  "Smell everyone's shoes and rank them from best to worst.",
];
