export const content = {
  mild: {
    truths: [
      "What's a talent you've never shown anyone here?",
      "What's your go-to karaoke song and why?",
      "If you could only eat one food forever, what would it be?",
      "What's the funniest thing that's ever happened to you?",
      "What's your biggest guilty pleasure?",
      "What's the strangest dream you can remember?",
      "What's one thing on your bucket list?",
      "If you had a superpower, what would it be and why?",
      "What's your biggest pet peeve?",
      "What's the most embarrassing song on your playlist?",
      "What childhood cartoon do you still secretly love?",
      "If you could live in any TV show world, which one?",
      "What's something you believed as a kid that was totally wrong?",
      "What's the weirdest food combination you actually enjoy?",
      "What's your go-to comfort movie?",
      "What's a skill you wish you had?",
      "What's the last thing that made you laugh out loud?",
      "What's your most-used emoji and what does it say about you?",
      "If you wrote a book, what would it be about?",
      "What's one thing you're irrationally afraid of?",
    ],
    dares: [
      "Do your best animal impression for 15 seconds.",
      "Sing the chorus of a song the group picks.",
      "Do a silly dance for 20 seconds straight — no stopping.",
      "Do your best impression of a famous person without saying their name.",
      "Speak only in rhymes until your next turn.",
      "Let someone draw a small doodle on your arm.",
      "Teach everyone a made-up handshake right now.",
      "Moonwalk across the room and back.",
      "Act out a movie scene silently — group has to guess it.",
      "Do 10 jumping jacks while listing 5 world capitals.",
      "Make the funniest face you can and hold it for 10 seconds.",
      "Try to lick your elbow for 30 seconds.",
      "Do your best robot dance while humming a song.",
      "Say the alphabet backwards as fast as you can.",
      "Imitate a newscaster reporting on whatever is happening right now.",
      "Narrate everything you do for the next 2 minutes in a documentary voice.",
      "Do your best impression of a baby learning to walk.",
      "Pretend to swim across the room in slow motion.",
      "Talk in slow motion for the next 3 rounds.",
      "Compliment everyone in the room with a food-related compliment.",
    ],
  },

  spicy: {
    truths: [
      "What's the most embarrassing thing you've done in public?",
      "What's the worst lie you've told and got away with?",
      "What's a secret you've never told anyone in this room?",
      "Have you ever cheated on a test or exam?",
      "What's the last thing you searched that you'd be embarrassed about?",
      "Have you ever pretended to be sick to avoid someone?",
      "What's the most childish thing you still do?",
      "Have you ever said 'I love you' and not meant it?",
      "Have you ever stolen anything, even something small?",
      "What's the pettiest reason you've unfollowed or blocked someone?",
      "Have you ever ghosted someone you actually liked?",
      "What's the most embarrassing thing in your camera roll right now?",
      "When was the last time you cried and what caused it?",
      "Have you ever talked badly about someone who's in this room?",
      "What's a habit you have that you'd be embarrassed if people found out?",
      "Have you ever blamed someone else for something you did?",
      "Have you ever eaten food you dropped on the floor and said nothing?",
      "Have you ever read someone's messages without their knowledge?",
      "Who is the last person you stalked on social media?",
      "What's something you pretend to like but secretly can't stand?",
    ],
    dares: [
      "Do your best impression of someone in this room right now.",
      "Send a voice note to the last person you texted saying 'I have something important to tell you.'",
      "Let someone post anything to your Instagram/WhatsApp story for 60 seconds.",
      "Do 20 push-ups right now. No breaks.",
      "Speak only in an accent the group chooses for the next 3 rounds.",
      "Call a family member and say 'I need to confess something' then say 'I ate the last snack. Bye.'",
      "Do your best robot dance for 30 seconds.",
      "Let the person next to you go through your camera roll for 30 seconds.",
      "Eat a full spoonful of the spiciest condiment available.",
      "Hold a plank for 45 seconds.",
      "Let someone change your phone wallpaper to whatever they choose.",
      "Give every person in the room one genuine, specific compliment.",
      "Go outside and yell 'I BELIEVE I CAN FLY!' at full volume.",
      "Do a TikTok dance of the group's choice.",
      "Let the group style your hair however they want for the rest of the game.",
      "Call the 5th contact in your phone and sing Happy Birthday to them.",
      "Show the group the last 10 photos in your camera roll without skipping any.",
      "Do a dramatic reading of your most cringe text conversation.",
      "Recreate the most embarrassing photo from your camera roll.",
      "Smell everyone's shoes and rank them from best to worst.",
    ],
  },

  wild: {
    truths: [
      "What's the most embarrassing thing someone could find on your phone RIGHT NOW?",
      "Rate everyone in this room from most to least likely to end up famous.",
      "Confess something you've never told anyone and plan to take to your grave.",
      "Have you ever had genuine feelings for someone in this room?",
      "What's something you've done that you're genuinely ashamed of?",
      "Who's the last person you texted, and what was the conversation about?",
      "What would your ex say is your absolute worst habit?",
      "If you had to delete one person from your contacts forever, who would it be?",
      "What's the most money you've spent on something embarrassing?",
      "Describe your most awkward date in full detail.",
      "What's a secret you've been keeping from someone in this room?",
      "What's the most extreme thing you've done to get someone's attention?",
      "Have you ever faked being sick to avoid going somewhere with someone here?",
      "What is your most embarrassing search in your browser history right now?",
      "Rank everyone in this room in order of who you'd trust with your deepest secret.",
    ],
    dares: [
      "Let someone go through your Instagram DMs for 60 seconds.",
      "Post whatever the group writes to your social media (must stay up 1 hour).",
      "Text your ex 'I miss you' and show the group the response.",
      "Call your parent right now and say 'I have something important to confess' then improvise.",
      "Let the group look at your 10 most recent purchases.",
      "Exchange phones with the person to your left for 5 minutes.",
      "Let someone post a selfie to your Instagram with a caption of their choice.",
      "Eat a full tablespoon of whatever condiment the group agrees on.",
      "Let the group write and send a message to anyone in your contacts.",
      "Show the group your most recent voice notes.",
      "Let the group ask your phone's AI assistant 3 questions about you.",
      "Let someone rate your Spotify listening history out loud.",
      "Read out the last 5 things you googled.",
      "Do 30 seconds of your most embarrassing dance move in front of everyone.",
      "Let the group pick any contact and write a 3-sentence bio of your relationship with them.",
    ],
  },
};
