export const prompts = [
  { a: "Always be 10 minutes late to everything", b: "Always be 20 minutes early to everything" },
  { a: "Have unlimited money but no free time", b: "Have unlimited free time but no money" },
  { a: "Lose your phone forever", b: "Lose your wallet forever" },
  { a: "Only eat nasi lemak for the rest of your life", b: "Never eat nasi lemak again" },
  { a: "Be famous but broke", b: "Be rich but completely unknown" },
  { a: "Be able to fly", b: "Be able to become invisible" },
  { a: "Know exactly how you'll die", b: "Know exactly when you'll die" },
  { a: "Live in the city forever", b: "Live in a kampung forever" },
  { a: "Have 1 year of perfect health", b: "Have 10 years of mediocre health" },
  { a: "Be able to speak every language", b: "Be able to play every instrument" },
  { a: "Travel back in time", b: "Fast-forward to the future" },
  { a: "Be the funniest person in any room", b: "Be the smartest person in any room" },
  { a: "Fight 100 duck-sized horses", b: "Fight 1 horse-sized duck" },
  { a: "Always say exactly what you're thinking", b: "Never speak again" },
  { a: "Have no internet for 1 month", b: "Eat only plain rice for 1 month" },
  { a: "Be able to read minds", b: "Be able to pause and rewind time" },
  { a: "Be stuck in a lift with your ex", b: "Be stuck in a lift with your boss" },
  { a: "Have free flights for life", b: "Have free food at any restaurant for life" },
  { a: "Lose all your memories", b: "Never be able to make new memories" },
  { a: "Be the hero everyone hates", b: "Be the villain everyone loves" },
  { a: "Know the date of every person's death", b: "Know every person's deepest secret" },
  { a: "Never age physically after 25", b: "Stop aging mentally — forever wise at 70" },
  { a: "Have a rewind button for conversations", b: "Have a pause button on life" },
  { a: "Sleep 12 hours and feel amazing", b: "Sleep 4 hours and feel perfectly fine" },
  { a: "Never have to pay for petrol", b: "Never have to pay for groceries" },
  { a: "Be incredibly attractive but dumb", b: "Be a genius but below-average looking" },
  { a: "Have your search history shown to your parents", b: "Have your texts shown to your boss" },
  { a: "Only be able to whisper", b: "Only be able to shout" },
  { a: "Live without music forever", b: "Live without movies and TV forever" },
  { a: "Always smell bad no matter how much you shower", b: "Always have bad hair no matter what you do" },
];
